# Generated by Django 2.2.8 on 2021-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_pics', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Image')),
                ('is_second_yuxari', models.BooleanField(default=False, verbose_name='Second yuxari')),
                ('is_second_ashagi', models.BooleanField(default=False, verbose_name='Second asagi')),
                ('is_third_sol', models.BooleanField(default=False, verbose_name='Third sol')),
                ('is_third_sag', models.BooleanField(default=False, verbose_name='Third sag')),
                ('is_third_orta', models.BooleanField(default=False, verbose_name='Third orta')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banner',
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='SlideInfo',
        ),
    ]
